name: Github-Pages
on:
  push:
    branches: [ dev-rockleona ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Script
        run: make build
      
      - name: Deploy gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          force_orphan: true
          folder: public
