name: Github-Pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.57.2'
          extended: true

      - name: Build Script
        run: make build
      
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_DEPLOY }}
          publish_branch: dev-rockleona
          force_orphan: true
          publish_dir: public
